using HealthVault.Entity.Model;
using System;
using System.Collections.Generic;
using System.Linq;

namespace HealthVault.Shared.DataTables
{
    public partial class lut_general_usagesDataTable
    {
        public static lut_general_usages[] _Data =
            new lut_general_usages[]{
                new lut_general_usages() { Identifier = 1, table_name = "Male",  value = "MALE" },
                new lut_general_usages() { Identifier = 2, table_name = "Male",  value = "FEMALE" },
                new lut_general_usages() { Identifier = 3, table_name = "vaccinated",  value = "0" },
                new lut_general_usages() { Identifier = 4, table_name = "vaccinated",  value = "1" },
                new lut_general_usages() { Identifier = 5, table_name = "vaccinated",  value = "2" },
                new lut_general_usages() { Identifier = 6, table_name = "vaccinated",  value = "3" },
                new lut_general_usages() { Identifier = 7, table_name = "vaccinated",  value = "9" },
                new lut_general_usages() { Identifier = 8, table_name = "VI_Status",  value = "Vaccination card" },
                new lut_general_usages() { Identifier = 9, table_name = "VI_Status",  value = "HF registers" },
                new lut_general_usages() { Identifier = 10, table_name = "VI_Status",  value = "Verbal information" },
                new lut_general_usages() { Identifier = 11, table_name = "Measles Epi-linked",  value = "Yes" },
                new lut_general_usages() { Identifier = 12, table_name = "Measles Epi-linked",  value = "NO" },
                new lut_general_usages() { Identifier = 13, table_name = "Rubella Epi-linked",  value = "Yes" },
                new lut_general_usages() { Identifier = 14, table_name = "Rubella Epi-linked",  value = "NO" },
                new lut_general_usages() { Identifier = 15, table_name = "Type of specimen",  value = "Blood" },
                new lut_general_usages() { Identifier = 16, table_name = "Type of specimen",  value = "Serum" },
                new lut_general_usages() { Identifier = 17, table_name = "Type of specimen",  value = "Oral fluid" },
                new lut_general_usages() { Identifier = 18, table_name = "Type of specimen",  value = "Serum&Urine" },
                new lut_general_usages() { Identifier = 19, table_name = "Type of specimen",  value = "Serum&Throatswab" },
                new lut_general_usages() { Identifier = 20, table_name = "Type of specimen",  value = "Urine" },
                new lut_general_usages() { Identifier = 21, table_name = "Type of specimen",  value = "Throatswab" },
                new lut_general_usages() { Identifier = 22, table_name = "Type of specimen",  value = "Serum&Urine&Throatswab" },
                new lut_general_usages() { Identifier = 23, table_name = "Type of specimen",  value = "Urine&Oral fluid" },
                new lut_general_usages() { Identifier = 24, table_name = "Type of specimen",  value = "Throatswab& Oralfluid" },
                new lut_general_usages() { Identifier = 25, table_name = "Type of specimen",  value = "Urine&Oral fluid&Throatswab" },
                new lut_general_usages() { Identifier = 26, table_name = "Condition of specimen",  value = "Adequate" },
                new lut_general_usages() { Identifier = 27, table_name = "Condition of specimen",  value = "poor/Quantity" },
                new lut_general_usages() { Identifier = 28, table_name = "Condition of specimen",  value = "Poor/Date collected" },
                new lut_general_usages() { Identifier = 29, table_name = "Condition of specimen",  value = "Poor/Cont." },
                new lut_general_usages() { Identifier = 30, table_name = "Condition of specimen",  value = "Poor/coldchain" },
                new lut_general_usages() { Identifier = 31, table_name = "Condition of specimen",  value = "Poor/transportation" },
                new lut_general_usages() { Identifier = 32, table_name = "Condition of specimen",  value = "Poor/Other reasons" },
                new lut_general_usages() { Identifier = 33, table_name = "Measles_Kit",  value = "CHEMICON" },
                new lut_general_usages() { Identifier = 34, table_name = "Measles_Kit",  value = "DadeBehring" },
                new lut_general_usages() { Identifier = 35, table_name = "Measles_Kit",  value = "Human" },
                new lut_general_usages() { Identifier = 36, table_name = "Measles_Kit",  value = "Light Diagnostics" },
                new lut_general_usages() { Identifier = 37, table_name = "Measles_Kit",  value = "Novatek" },
                new lut_general_usages() { Identifier = 38, table_name = "Measles_Kit",  value = "UDI" },
                new lut_general_usages() { Identifier = 39, table_name = "Rubella_Kit",  value = "CHEMICON" },
                new lut_general_usages() { Identifier = 40, table_name = "Rubella_Kit",  value = "DadeBehring" },
                new lut_general_usages() { Identifier = 41, table_name = "Rubella_Kit",  value = "Human" },
                new lut_general_usages() { Identifier = 42, table_name = "Rubella_Kit",  value = "Light Diagnostics" },
                new lut_general_usages() { Identifier = 43, table_name = "Rubella_Kit",  value = "Novatek" },
                new lut_general_usages() { Identifier = 44, table_name = "Rubella_Kit",  value = "UDI" },
                new lut_general_usages() { Identifier = 45, table_name = "Measles ELISA",  value = "IgM+ve" },
                new lut_general_usages() { Identifier = 46, table_name = "Measles ELISA",  value = "IgM-ve" },
                new lut_general_usages() { Identifier = 47, table_name = "Measles ELISA",  value = "Unknown" },
                new lut_general_usages() { Identifier = 48, table_name = "Measles ELISA",  value = "equivocal" },
                new lut_general_usages() { Identifier = 49, table_name = "Rubella ELISA",  value = "IgM+ve" },
                new lut_general_usages() { Identifier = 50, table_name = "Rubella ELISA",  value = "IgM-ve" },
                new lut_general_usages() { Identifier = 51, table_name = "Rubella ELISA",  value = "Unknown" },
                new lut_general_usages() { Identifier = 52, table_name = "Rubella ELISA",  value = "equivocal" },
                new lut_general_usages() { Identifier = 53, table_name = "Id_Source",  value = "Sporadic case" },
                new lut_general_usages() { Identifier = 54, table_name = "Id_Source",  value = "Chain of transmission" },
                new lut_general_usages() { Identifier = 55, table_name = "Id_Source",  value = "Epidemic" },
                new lut_general_usages() { Identifier = 56, table_name = "Id_Source",  value = "Imported" },
                new lut_general_usages() { Identifier = 57, table_name = "Id_Source",  value = "Import related" },
                new lut_general_usages() { Identifier = 58, table_name = "Id_Source",  value = "Other" },
                new lut_general_usages() { Identifier = 59, table_name = "FINAL DIGNOSIS",  value = "Measles Lab confirmed" },
                new lut_general_usages() { Identifier = 60, table_name = "FINAL DIGNOSIS",  value = "Measles Epi-Linked" },
                new lut_general_usages() { Identifier = 61, table_name = "FINAL DIGNOSIS",  value = "Measles Clinicaly diagnosed" },
                new lut_general_usages() { Identifier = 62, table_name = "FINAL DIGNOSIS",  value = "Rubella Lab confirmed" },
                new lut_general_usages() { Identifier = 63, table_name = "FINAL DIGNOSIS",  value = "Rubella Epi-Linked" },
                new lut_general_usages() { Identifier = 64, table_name = "FINAL DIGNOSIS",  value = "Rubella Clinicaly diagnosed" },
                new lut_general_usages() { Identifier = 65, table_name = "FINAL DIGNOSIS",  value = "Discarded case" },
                new lut_general_usages() { Identifier = 66, table_name = "FINAL DIGNOSIS",  value = "Vaccine related case" },
                new lut_general_usages() { Identifier = 67, table_name = "FINAL DIGNOSIS",  value = "Serosurvey assesment" },
                new lut_general_usages() { Identifier = 68, table_name = "FINAL DIGNOSIS",  value = "Other RFI" },
                new lut_general_usages() { Identifier = 69, table_name = "FINAL DIGNOSIS",  value = "Double infection" },
                new lut_general_usages() { Identifier = 70, table_name = "FINAL DIGNOSIS",  value = "imported case" },
                new lut_general_usages() { Identifier = 71, table_name = "Type2ndSpecimen",  value = "Recovered" },
                new lut_general_usages() { Identifier = 72, table_name = "Type2ndSpecimen",  value = "Complicated" },
                new lut_general_usages() { Identifier = 73, table_name = "Type2ndSpecimen",  value = "Died" },
                new lut_general_usages() { Identifier = 74, table_name = "Type2ndSpecimen",  value = "Lost track of case" },
                new lut_general_usages() { Identifier = 75, table_name = "VG_Measles_RT-PCR",  value = "YES" },
                new lut_general_usages() { Identifier = 76, table_name = "VG_Measles_RT-PCR",  value = "NO" },
                new lut_general_usages() { Identifier = 77, table_name = "VG_Rubella_RT-PCR",  value = "YES" },
                new lut_general_usages() { Identifier = 78, table_name = "VG_Rubella_RT-PCR",  value = "NO" },
                new lut_general_usages() { Identifier = 79, table_name = "measles_genotype",  value = "A" },
                new lut_general_usages() { Identifier = 80, table_name = "measles_genotype",  value = "B1" },
                new lut_general_usages() { Identifier = 81, table_name = "measles_genotype",  value = "B2" },
                new lut_general_usages() { Identifier = 82, table_name = "measles_genotype",  value = "B3" },
                new lut_general_usages() { Identifier = 83, table_name = "measles_genotype",  value = "C1" },
                new lut_general_usages() { Identifier = 84, table_name = "measles_genotype",  value = "C2" },
                new lut_general_usages() { Identifier = 85, table_name = "measles_genotype",  value = "D1" },
                new lut_general_usages() { Identifier = 86, table_name = "measles_genotype",  value = "D2" },
                new lut_general_usages() { Identifier = 87, table_name = "measles_genotype",  value = "D3" },
                new lut_general_usages() { Identifier = 88, table_name = "measles_genotype",  value = "D4" },
                new lut_general_usages() { Identifier = 89, table_name = "measles_genotype",  value = "D5" },
                new lut_general_usages() { Identifier = 90, table_name = "measles_genotype",  value = "D6" },
                new lut_general_usages() { Identifier = 91, table_name = "measles_genotype",  value = "D7" },
                new lut_general_usages() { Identifier = 92, table_name = "measles_genotype",  value = "D8" },
                new lut_general_usages() { Identifier = 93, table_name = "measles_genotype",  value = "D9" },
                new lut_general_usages() { Identifier = 94, table_name = "measles_genotype",  value = "D10" },
                new lut_general_usages() { Identifier = 95, table_name = "measles_genotype",  value = "F" },
                new lut_general_usages() { Identifier = 96, table_name = "measles_genotype",  value = "G1" },
                new lut_general_usages() { Identifier = 97, table_name = "measles_genotype",  value = "G2" },
                new lut_general_usages() { Identifier = 98, table_name = "measles_genotype",  value = "G3" },
                new lut_general_usages() { Identifier = 99, table_name = "measles_genotype",  value = "H1" },
                new lut_general_usages() { Identifier = 100, table_name = "measles_genotype",  value = "H2" },
                new lut_general_usages() { Identifier = 101, table_name = "rubella_genotype",  value = "1B" },
                new lut_general_usages() { Identifier = 102, table_name = "rubella_genotype",  value = "1g" },
                new lut_general_usages() { Identifier = 103, table_name = "rubella_genotype",  value = "1a" },
                new lut_general_usages() { Identifier = 104, table_name = "rubella_genotype",  value = "1c" },
                new lut_general_usages() { Identifier = 105, table_name = "rubella_genotype",  value = "1E" },
                new lut_general_usages() { Identifier = 106, table_name = "rubella_genotype",  value = "1D" },
                new lut_general_usages() { Identifier = 107, table_name = "rubella_genotype",  value = "2A" },
                new lut_general_usages() { Identifier = 108, table_name = "rubella_genotype",  value = "2B" },
                new lut_general_usages() { Identifier = 109, table_name = "rubella_genotype",  value = "2c" },
                new lut_general_usages() { Identifier = 110, table_name = "rubella_genotype",  value = "1F" },
                new lut_general_usages() { Identifier = 111, table_name = "Sero_Kit",  value = "CHEMICON" },
                new lut_general_usages() { Identifier = 112, table_name = "Sero_Kit",  value = "DadeBehring" },
                new lut_general_usages() { Identifier = 113, table_name = "Sero_Kit",  value = "Human" },
                new lut_general_usages() { Identifier = 114, table_name = "Sero_Kit",  value = "Light Diagnostics" },
                new lut_general_usages() { Identifier = 115, table_name = "Sero_Kit",  value = "Novatek" },
                new lut_general_usages() { Identifier = 116, table_name = "Sero_Kit",  value = "UDI" },
                new lut_general_usages() { Identifier = 117, table_name = "Sample_Sent2RL",  value = "YES" },
                new lut_general_usages() { Identifier = 118, table_name = "Sample_Sent2RL",  value = "NO" },
                new lut_general_usages() { Identifier = 119, table_name = "Sero_Measles_IgM",  value = "Positive" },
                new lut_general_usages() { Identifier = 120, table_name = "Sero_Measles_IgM",  value = "Negative" },
                new lut_general_usages() { Identifier = 121, table_name = "Sero_Measles_IgM",  value = "Unknown" },
                new lut_general_usages() { Identifier = 122, table_name = "Sero_Measles_IgM",  value = "Equivocal" },
                new lut_general_usages() { Identifier = 123, table_name = "Sero_Measles_IgG",  value = "Positive" },
                new lut_general_usages() { Identifier = 124, table_name = "Sero_Measles_IgG",  value = "Negative" },
                new lut_general_usages() { Identifier = 125, table_name = "Sero_Rubella_IgM",  value = "Positive" },
                new lut_general_usages() { Identifier = 126, table_name = "Sero_Rubella_IgM",  value = "Negative" },
                new lut_general_usages() { Identifier = 127, table_name = "Sero_Rubella_IgM",  value = "Unknown" },
                new lut_general_usages() { Identifier = 128, table_name = "Sero_Rubella_IgM",  value = "Equivocal" },
                new lut_general_usages() { Identifier = 129, table_name = "Sero_Rubella_IgG",  value = "Positive" },
                new lut_general_usages() { Identifier = 130, table_name = "Sero_Rubella_IgG",  value = "Negative" },
                new lut_general_usages() { Identifier = 131, table_name = "IFA_Status",  value = "Adequate" },
                new lut_general_usages() { Identifier = 132, table_name = "IFA_Status",  value = "Poor/transportation delay" },
                new lut_general_usages() { Identifier = 133, table_name = "IFA_Status",  value = "Poor/collection delay" },
                new lut_general_usages() { Identifier = 134, table_name = "IFA_Status",  value = "Poor/quantity problem" },
                new lut_general_usages() { Identifier = 135, table_name = "IFA_Status",  value = "Poor/coldchain problem" },
                new lut_general_usages() { Identifier = 136, table_name = "IFA_Status",  value = "Other" },
                new lut_general_usages() { Identifier = 137, table_name = "VI_Vero_SLAM",  value = "Present" },
                new lut_general_usages() { Identifier = 138, table_name = "VI_Vero_SLAM",  value = "Absent" },
                new lut_general_usages() { Identifier = 139, table_name = "IFA",  value = "Mab.Rubella" },
                new lut_general_usages() { Identifier = 140, table_name = "IFA",  value = "Mab.Measles" },
                new lut_general_usages() { Identifier = 141, table_name = "VI_B95a",  value = "Present" },
                new lut_general_usages() { Identifier = 142, table_name = "VI_B95a",  value = "Absent" }
           };

        public static IEnumerable<lut_general_usages> GetTable(string stTableName)
        {
            if(String.IsNullOrEmpty(stTableName) == false)
            {
                return from t in _Data
                       where t.table_name == stTableName
                       select t;
            }
            else
                throw new ArgumentOutOfRangeException("stTableName Is Missing");
        }
    }
}
