// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HealthVault.Entity.Model;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using HealthVault.Entity.Model;

namespace HealthVault.Entity.Context
{
    public partial class HealthvaultContext : DbContext
    {
        public HealthvaultContext()
        {
        }

        public HealthvaultContext(DbContextOptions<HealthvaultContext> options)
            : base(options)
        {
        }

        public virtual DbSet<LUTGovernorates> LUTGovernorates { get; set; }
        public virtual DbSet<LUTOrganizationType> LUTOrganizationType { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=localhost;Initial Catalog=HealthVault;User ID=sa;Password=get@get1");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<LUTGovernorates>(entity =>
            {
                entity.Property(e => e.Name).HasMaxLength(50);
            });

            modelBuilder.Entity<LUTOrganizationType>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(100);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}