
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HealthVault.Entity.Model
{
    public partial class lut_general_usages
    {
        public short Identifier { get; set; }
        public string table_name { get; set; }
        public string value { get; set; }
    }
}