// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HealthVault.Entity.Model
{
    public partial class lut_organizationtype
    {
        public short Identifier { get; set; }
        public string Name { get; set; }
    }
}