// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HealthVault.Entity.Model
{
    public partial class organization
    {
        public static organization ConvertParams(string Identifier, string active, string type,
                           string address_city, string address_state, string partOf)
        {
            organization NewObj = new organization();

            // Convert Identifier
            if (false == string.IsNullOrEmpty(Identifier))
                NewObj.identifier = int.Parse(Identifier);

            // Convert addressCity
            if (false == string.IsNullOrEmpty(address_city))
            {
                short temp;
                if (false == short.TryParse(address_city, out temp))
                    throw new ArgumentOutOfRangeException("address_city");
                else
                    NewObj.address_city = temp;
            }
                

            // Convert partof
            if (false == string.IsNullOrEmpty(partOf))
                NewObj.partOf = int.Parse(partOf);

            return NewObj;
        }
    }
}