// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HealthVault.Entity.Model
{
    public partial class organization
    {
        public int identifier { get; set; }
        public bool? active { get; set; }
        public short? type { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public string telecom { get; set; }
        public string telecom1 { get; set; }
        public string telecom2 { get; set; }
        public string address { get; set; }
        public short? city { get; set; }
        public int? partOf { get; set; }
    }
}