// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HealthVault.Entity.Model
{
    public partial class Patient
    {
        public string identifier { get; set; }
        public int Record_ID { get; set; }
        public bool? active { get; set; }
        public string name { get; set; }
        public string familyname { get; set; }
        public string telecom { get; set; }
        public string telecom1 { get; set; }
        public string telecom2 { get; set; }
        public bool? gender { get; set; }
        public DateTime? birthDate { get; set; }
        public bool? deceased { get; set; }
        public DateTime? deceasedDate { get; set; }
    }
}