// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HealthVault.Entity.Model
{
    public partial class patient
    {
        public string identifier { get; set; }
        public int Record_ID { get; set; }
        public bool? active { get; set; }
        public string name { get; set; }
        public string familyname { get; set; }
        public string telecom { get; set; }
        public string telecom1 { get; set; }
        public string telecom2 { get; set; }
        public bool? gender { get; set; }
        public DateTime? birth_date { get; set; }
        public short? birth_city { get; set; }
        public string address { get; set; }
        public short? address_city { get; set; }
        public short? address_country { get; set; }
        public short? address_state { get; set; }
        public string email { get; set; }
        public bool? deceased { get; set; }
        public DateTime? deceased_date { get; set; }
    }
}